# .travis.yml
sudo: required

language: python
python:
  - "3.6"

install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - helm init --client-only

script:
  - helm lint library/* 
