sudo: required
language: python
python:
- '3.6'
install:
- curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
- helm init --client-only
- pip install chartpress
script:
- helm lint library/*
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
- chmod 400 deploy_key
env:
- GIT_SSH_COMMAND="ssh -i ${PWD}/deploy_key"
deploy:
- provider: script
  skip_cleanup: true
  script: chartpress --publish-chart
  on:
    branch: master
    tags: true
