{{- define "service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{  .Values.service.type }}
  selector:
    {{- include "chart.labels" . | nindent 4 }}
  ports:
  {{- range $spec := .Values.service.specs }}
  - name: {{ $spec.name }}
    port: {{ $spec.port }}
    protocol: {{ $spec.protocol | default "TCP" }}
          {{- if $spec.targetPort }}
    targetPort: {{ $spec.targetPort }}
          {{- end}}
      {{- if  $spec.nodePort }}
    nodePort: {{  $spec.nodePort }}
        {{- end }}
   {{- end -}}
{{- end -}}